version: "3.7"
services:
  expose:
    build: ./
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080 # adjust port here HOST:CONTAINER
    env_file: ./.env
    restart: unless-stopped
    volumes:
      - ./expose.db:/root/.expose
